-- USE subordination_structure_production;
INSERT INTO `employees` (`name`, `created_at`, `updated_at`) VALUES ('Иванов А.А.', NOW(), NOW());
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Петров И.Н.', NOW(), NOW(), '1');
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Сидоров М.С.', NOW(), NOW(), '1/2');
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Михайлов Н.К.', NOW(), NOW(), '1/2/3');
INSERT INTO `employees` (`name`, `created_at`, `updated_at`) VALUES ('Ган В.А.', NOW(), NOW());
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Деревянный Н.Н.', NOW(), NOW(), '5');
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Покров С.П.', NOW(), NOW(), '5/6');
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Михайлов Н.К.', NOW(), NOW(), '5/6/7');
INSERT INTO `employees` (`name`, `created_at`, `updated_at`) VALUES ('Крамов А.В.', NOW(), NOW());
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Маров В.А.', NOW(), NOW(), '9');
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Петлюра В.С.', NOW(), NOW(), '9');
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Смирнов А.Е.', NOW(), NOW(), '10');
INSERT INTO `employees` (`name`, `created_at`, `updated_at`) VALUES ('Птичкин Н.М.', NOW(), NOW());
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Смешной Е.В.', NOW(), NOW(),'13');
INSERT INTO `employees` (`name`, `created_at`, `updated_at`, `ancestry`) VALUES ('Поддубный Н.И.', NOW(), NOW(), '14');
